### PR TITLE
Removed `@storybook/storybook-deployer`

### LINKED ISSUE #96: Critical dependency vulnerability from `storybook-deployer`
Thanks for the wonderful template 👍 

Currently there's a critical vulnerability when running `npm install` 👇

image

And it's coming from `@storybook/storybook-deployer` which is deprecated (check archived repo [here](https://github.com/storybook-eol/storybook-deployer))

### Solution

We can simply remove `@storybook/storybook-deployer` from the dependencies and it will clear all vulnerabilities.

### PR DESCRIPTION
**Pull request by zaaakher**
Fixes #96

### CODE REVIEW

**Comment by TimMikeladze** [comment]
Thank you for the PR. 

I did not know that the storybook deployer is deprecated, however we can't just remove it since it's used as part of the GitHub actions to deploy storybook to GitHub pages when a new package version gets published. 

Do you mind replacing it with this alternative?

https://github.com/bitovi/github-actions-storybook-to-github-pages

**Comment by zaaakher** [comment]
I just pushed a commit updating `publish.yml`

@TimMikeladze kindly take a look if its correct

**Comment by TimMikeladze** [comment]
I'm closing this PR and sent another one #98 since I had to make updates to the lock file and fix the commit messages so they pass the linter.

I included you as a co-author on the comit.

Thanks!

**Comment by zaaakher** [comment]
Awesome, thanks bro 👍

**Pull request closed without merging**
